// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3oC5QpcjG4SQ4WapmIUHT6ThiwAd7KZU',
    appId: '1:1054619461777:web:6787bc7633d98d275b7730',
    messagingSenderId: '1054619461777',
    projectId: 'thesis-c8a70',
    authDomain: 'thesis-c8a70.firebaseapp.com',
    storageBucket: 'thesis-c8a70.firebasestorage.app',
    measurementId: 'G-Y8TK00T3GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAenO9hyYVvZRVaRWveyXiw8s5yGpg_bCA',
    appId: '1:1054619461777:android:fdf68ce6a800affe5b7730',
    messagingSenderId: '1054619461777',
    projectId: 'thesis-c8a70',
    storageBucket: 'thesis-c8a70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfrI9eChd2oCdvt2zG4E5Xr4JvPi7hi4s',
    appId: '1:1054619461777:ios:335d4d39cd7842f95b7730',
    messagingSenderId: '1054619461777',
    projectId: 'thesis-c8a70',
    storageBucket: 'thesis-c8a70.firebasestorage.app',
    iosBundleId: 'com.biodigit.biodigitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfrI9eChd2oCdvt2zG4E5Xr4JvPi7hi4s',
    appId: '1:1054619461777:ios:335d4d39cd7842f95b7730',
    messagingSenderId: '1054619461777',
    projectId: 'thesis-c8a70',
    storageBucket: 'thesis-c8a70.firebasestorage.app',
    iosBundleId: 'com.biodigit.biodigitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3oC5QpcjG4SQ4WapmIUHT6ThiwAd7KZU',
    appId: '1:1054619461777:web:0804dc699f2fd4035b7730',
    messagingSenderId: '1054619461777',
    projectId: 'thesis-c8a70',
    authDomain: 'thesis-c8a70.firebaseapp.com',
    storageBucket: 'thesis-c8a70.firebasestorage.app',
    measurementId: 'G-VBQ96EZ0D2',
  );
}
